[GLOBAL]
pants_version = "2.31.0"
pythonpath = ["%(buildroot)s/pants-plugins"]
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.providers.experimental.python_build_standalone",
  "pants.backend.plugin_development",
  "pkl",
]

[source]
root_patterns = ["pants-plugins", "/"]

[python]
enable_resolves = true
interpreter_constraints = [">=3.9,<3.14"]

[python.resolves]
python-default = "3rdparty/python/default.lock"
pants-plugins = "pants-plugins/lock.txt"

[python.resolves_to_interpreter_constraints]
pants-plugins = ["==3.11.*"]
